name: Karohy backend - CI Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  Build_Deploy_Prod:
    strategy:
      matrix:
        environment: production
    steps:
      - template: .github/workflows/build-deploy-template.yml